[env]
PROJECT_NAME = "my-awesome-copilot"

[settings]
experimental = true

[tools]
gitversion = { version = "6.5.1" }
pre-commit = { version = "4.5" }
python = { version = "3.14" }

[task_config]
includes = [".mise-shared-tasks"]

[tasks.download-shared-tasks]
description = "Download shared tasks"
hide = true
file = "git::ssh://git@github.com/jterral/my-mise-tasks.git//shared-tasks/download-tasks?ref=main"

[tasks.apply-shared-tasks]
description = "ðŸ“© Download shared tasks in the current workspace"
wait_for = "download-shared-tasks"
run = "mise download-shared-tasks --directory .mise-shared-tasks main precommit"

[tasks.info]
description = "Print project information"
quiet = true
run = '''
echo ""
echo "â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€"
echo "  ðŸ“¦ Project information"
echo "â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€"
echo ""
echo "  Project           : $PROJECT_NAME"
echo "  Package version   : $PACKAGE_VERSION"
echo ""
echo "  Tooling"
echo "  â”€â”€â”€â”€â”€â”€â”€"
echo "  gitversion        : $(gitversion -version)"
echo "  python            : $(python --version | awk '{print $2}')"
echo "  pre-commit        : $(pre-commit --version | awk '{print $2}')"
echo ""
'''
