name: sync-github-awesome-copilot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/checkout@v6
        with:
          repository: github/awesome-copilot
          path: github-awesome-copilot

      - name: ðŸ”„ Sync GitHub Awesome Copilot files
        run: |
          cp ./github-awesome-copilot/instructions/agent-skills.instructions.md ./synced/github-awesome-copilot/instructions/agent-skills.instructions.md
          cp ./github-awesome-copilot/instructions/agents.instructions.md ./synced/github-awesome-copilot/instructions/agents.instructions.md
          cp ./github-awesome-copilot/instructions/code-review-generic.instructions.md ./synced/github-awesome-copilot/instructions/code-review-generic.instructions.md
          cp ./github-awesome-copilot/instructions/instructions.instructions.md ./synced/github-awesome-copilot/instructions/instructions.instructions.md
          cp ./github-awesome-copilot/instructions/prompt.instructions.md ./synced/github-awesome-copilot/instructions/prompt.instructions.md

      - uses: peter-evans/create-pull-request@v8
        with:
          branch: "feature/sync-github-awesome-copilot"
          title: "feat(sync): sync github awesome copilot files"
          body: This PR syncs the latest files from the GitHub Awesome Copilot repository.
          labels: automated-sync
